### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by timmy-mac** [lukecarr/ollivander#2]
Hi Luke,

Just checking you know that the docs page is down (or not yet created? - I appreciate it's quite a new project.)

Nothing in DNS for ollivander.lukecarr.dev

Really looking forward to having a look.

Thanks for sharing,
Tim

**Comment by lukecarr** [comment]
Hi Tim,

Documentation is still on the todo list at the moment I'm afraid. Sorry for the confusion in pre-emptively linking to it ine README!

I'll ping you on this issue when the docs are ready!

**Comment by lukecarr** [comment]
Hi Tim,

Apologies for the delay on this issue. I've been sidetracked with work and other projects for quite a while now.

v2.0.0 has just been released, which includes a full rewrite with fewer dependencies, better TypeScript support, and more features. There's a fairly comprehensive guide in the README now, and I'm working on a more fleshed-out docs site as well.
